### ISSUE TITLE
Add option to use Random.org API as the random engine instead of Math.random()

### ISSUE THREAD

**Issue by slavabez** [slavabez/yadicer#5]
Use [https://www.random.org/clients/http/api/](https://www.random.org/clients/http/api/) to add true randomness to the rolls.

Use the config that is passed to the main function, and `axios` can be used for making the http requests, but any suggestions are welcome!

If nobody picks this up in a day or two I'll have a go myself

**Comment by tarsir** [comment]
I'll go ahead and grab this one!

**Comment by slavabez** [comment]
Neat, thanks!

**Comment by slavabez** [comment]
@tarsir by the way, any help is welcome, including unfinished code, so no pressure if you can't or don't want to finish!

**Comment by tarsir** [comment]
No worries, I'm almost done I think :P

**Comment by slavabez** [comment]
Awesome, I'll be sure to review it tomorrow!

**Comment by slavabez** [comment]
Resolved thanks to great work by @tarsir
